name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - sphinx<8.0
  - myst-parser
  - sphinx_rtd_theme
  - sphinxcontrib-mermaid
  - requests>=2.32.0
  - snowballstemmer
  - setuptools>=78.1.1
  - urllib3>=2.2.2
  - pip
  - pip:
    - sphinxcontrib.googleanalytics
    - sphinx-markdown-tables
    - clang
    - zipp>=3.19.1
